//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ruhe.TestWeb.Web.UI.Controls {
    
    
    public partial class InputEnumTests {
        
        /// <summary>
        /// noInitialBlank control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ruhe.Web.UI.Controls.InputEnumeration<Ruhe.Month> noInitialBlank;
        
        /// <summary>
        /// initialBlank control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Ruhe.Web.UI.Controls.InputEnumeration<Ruhe.Month> initialBlank;
    }
}
