//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public partial class Sample {
    
    /// <summary>
    /// confirmationMessage control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ruhe.Web.UI.Controls.Message confirmationMessage;
    
    /// <summary>
    /// name control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ruhe.Web.UI.Controls.InputTextBox name;
    
    /// <summary>
    /// email control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ruhe.Web.UI.Controls.InputEmailAddress email;
    
    /// <summary>
    /// date control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ruhe.Web.UI.Controls.InputDate date;
    
    /// <summary>
    /// age control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ruhe.Web.UI.Controls.InputInteger age;
    
    /// <summary>
    /// height control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ruhe.Web.UI.Controls.InputNumber height;
    
    /// <summary>
    /// range control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ruhe.Web.UI.Controls.InputDateRange range;
    
    /// <summary>
    /// comments control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ruhe.Web.UI.Controls.InputTextBox comments;
    
    /// <summary>
    /// AnotherLayoutContainer1 control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ruhe.TestWeb.AnotherLayoutContainer AnotherLayoutContainer1;
    
    /// <summary>
    /// saveButton control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ruhe.Web.UI.Controls.SaveButton saveButton;
}
