//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



/// <summary>
/// Web_UI_Controls_LabeledControlPanelTests class.
/// </summary>
/// <remarks>
/// Auto-generated class.
/// </remarks>
public partial class Web_UI_Controls_LabeledControlPanelTests {
    
    /// <summary>
    /// panel control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ruhe.Web.UI.Controls.LabeledControlPanel panel;
    
    /// <summary>
    /// textbox control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::Ruhe.Web.UI.Controls.InputTextBox textbox;
}
